### PR TITLE
Adding custom engines

### PR DESCRIPTION
**Pull request by omerxx**
Adding the ability to use a custom code searcher like https://github.com/ggreer/the_silver_searcher.

I use `ag` regularly instead of grep. It's faster and easier visually so I created this small addition.
The only important thing to note is having the flags set up in the .gf json file. Tried to make it clear as possible in the readme. 

I hope you'll like it!

### CODE REVIEW

**Comment by tomnomnom** [comment]
Yo!

In general I think this is a good idea, but because the flags are often incompatible as you mention in the changes to the README: I think it would make more sense to specify the engine in the JSON file rather than as a command-line argument.

Thoughts?

**Comment by omerxx** [comment]
@tomnomnom TBH I actually started doing exactly that but felt it was hiding the option in a config file. Would you say that's a better option? I would happily do that.

**Comment by tomnomnom** [comment]
I think it makes the most sense!

The flag compatibility thing means that the alternative is having to remember which engine to use with which pattern which would be really tricky IMO. This is assuming you have patterns that require different engines of course.

**Comment by omerxx** [comment]
You're right!
I'll move it as a parameter on the JSON file.

**Comment by omerxx** [comment]
@tomnomnom Let me know if it makes more sense now. 
BTW - sorry for the empty spaces removals, I've set Vim to do it for me automatically...

**Comment by tomnomnom** [comment]
Sorry for the delay; merged! Thank you so much :)

**Comment by EdOverflow** [comment]
Now I can use ripgrep! \o/

**Pull request merged**
